version: '3.4'
services:
  mysql:
    restart: always
    image: "mysql:5.7.30"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/mysql
      - "./mysql/log:/var/log/mysql"
  postgres:
    restart: always
    image: "postgres:9.5.19-alpine"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/postgres
    environment:
      - POSTGRES_PASSWORD=pass
      - PGDATA=/data
  redis:
    image: "redis:3.0.6-alpine"
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
    - ./redis:/usr/local/etc/redis/
    restart: always
  rcli:
    image: "redis:3.0.6-alpine"
    links:
      - redis
    # docker-compose run rcli
    command: >
      redis-cli -h redis
  rabbit:
    image: rabbitmq:3.7.14-alpine
    ports:
      - "5672:5672"
  memcached:
    image: memcached:1.4.25
    ports:
      - "11211:11211"
    command: memcached -vv
volumes:
  postgres_data:
  mysql_data:
  mysql_log:
    driver: local
  mysql_conf:
    driver: local
